apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-{{ template "verity.fullname" . }}
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "{{ .Values.secrets.awsSecretsNameCredentialsTf }}"
          objectType: "secretsmanager"
          objectAlias: "credentials-tf.json"